config/routes.rb
Rails.application.routes.draw do

	get ':zipcode' 	=> 'forecasts#show', as: 'forecast'
	get '95765' 		=> 'forecasts#show', as: 'rocklin'
  resources :forecasts, only: [:create]

  root to: redirect('/95765')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/icon_lookup.rb
module IconLookup
  extend ActiveSupport::Concern

  included do

    def icon_image
      icon_map = {
        "clear-day": "Sun.png",
        "clear-night": "Moon.png",
        "rain": "Cloud-Rain.png",
        "snow": "Snowflake.png",
        "sleet": "Cloud-Snow.png",
        "wind": "Wind.png",
        "fog": "Cloud-Fog-Alt.png",
        "cloudy": "Cloud.png",
        "partly-cloudy-day": "Cloud-Sun.png",
        "partly-cloudy-night": "Cloud-Moon.png"
      }
      icon_map[icon.to_sym]
    end
  end

end

app/models/extended_forecast.rb
class ExtendedForecast < ApplicationRecord
	include IconLookup

	belongs_to :forecast

	default_scope { order(date: :asc) }

end

app/models/forecast.rb
class Forecast < ApplicationRecord
	include IconLookup

	attr_accessor :api_data

	belongs_to :location
	has_many :extended_forecasts, dependent: :destroy

	after_initialize :set_location, if: :new_record?
	before_save :process_weather_data

	validates :location, absence: false
	validates :search, presence: true


	def to_param
		location.zipcode
	end

	def self.api_lookup(location)
		lat, lon = location.coords
		ForecastIO.forecast(lat, lon)
	end
	def api_lookup
		self.api_data = Forecast.api_lookup(location)
	end


	def self.set_location(search)
		Location.string_lookup(search)
	end
	def set_location
		self.location = Forecast.set_location(search)
	end

	def already_exists?
		load_existing.present?
	end

	def load_existing
		Location.find(location.id).forecast if location.present?
	end

	protected

		def process_weather_data
			api_lookup

			extended_forecasts.clear

			currently = api_data.currently
			self.date = Time.at(currently.time)
			self.current_temp = currently.temperature
			self.icon = currently.icon

			daily = api_data.daily.data

			daily.each do |day|
				time = Time.at(day.time)
				if time.to_date == Time.now.to_date
					self.high_temp = day.temperatureHigh
					self.low_temp  = day.temperatureLow
				else
					ef = ExtendedForecast.new date: time, icon: day.icon, high_temp: day.temperatureHigh, low_temp: day.temperatureLow
					self.extended_forecasts << ef
				end
			end
		end

end

app/models/location.rb
class Location < ApplicationRecord

  has_one :forecast, dependent: :destroy


  def has_dst?; daylight_savings; end

  def self.parse_city(city)
  	return nil if city.blank?
    city = city.strip
    city = city.squeeze(" ")
    city = city.gsub(/-/, " ")
    city = city.gsub(/\./, "")
    city = city.sub(/^st\s(.+)/i, 'Saint \1')    # convert St to Saint
    city = city.sub(/^ste\s(.+)/i, 'Sainte \1')  # convert Ste to Sainte
    city = city.sub(/^mt\s(.+)/i, 'Mount \1')    # convert Mt to Mount
    city = city.sub(/^ft\s(.+)/i, 'Fort \1')     # convert Ft to Fort
    city
  end

  def self.parse_zipcode(zipcode)
  	return nil if zipcode.blank?
    zipcode.strip.gsub /[^0-9]/, ''
  end

  def self.string_lookup(location_string)
  	return nil if location_string.blank?
    zipcode = location_string.tr('^[0-9]', '')
    city, state = location_string.tr('[0-9]', '').split(',')
    lookup(city, state, zipcode)
  end

  def self.lookup(city, state, zipcode)
  	zipcode = Location.parse_zipcode(zipcode)
    location = Location.where(:zipcode => zipcode).first
    if location.blank?
	  	city = Location.parse_city(city).try(:upcase)
	  	state = state.upcase.strip unless state.blank?
      location = Location.where("UPPER(city) = ? AND state = ?", city, state).first
    end
    location
  end


  def coords
  	[latitude, longitude]
  end

  def to_s
    "#{city}, #{state}"
  end


  # for testing
  def self.sac
    where(city: 'Sacramento', state: 'CA').first
  end

  def self.ny
    where(city: 'New York', state: 'NY').first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_forecast, only: [:show]

  def show
    unless load_or_create_forecast
      flash[:alert] = "Couldn't find #{@forecast.search}. Make sure to include the state if entering a city."
      redirect_to root_path
    end
    @cached = fragment_exist?(@forecast.cache_key_with_version)
  end

  def create
    @forecast = Forecast.new(forecast_params)
    if @forecast.search.blank?
      redirect_to root_path
      return
    end

    respond_to do |format|
      if load_or_create_forecast
        format.html { redirect_to @forecast }
      else
        format.html { redirect_to rocklin_path, alert: "Couldn't find #{@forecast.search}. Make sure to include the state if entering a city." }
      end
    end
  end


  private

    def load_or_create_forecast
      # debugger
      if @forecast.already_exists?
        @forecast = @forecast.load_existing
        if fragment_exist?(@forecast.cache_key_with_version)
          @success = true
        else
          @forecast.touch
          @success = @forecast.save
        end
      else
        @success = @forecast.save
      end
      @success
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_forecast
      @forecast = Location.where(zipcode: params[:zipcode]).first.try(:forecast)
      if @forecast.blank?
        @forecast = Forecast.new(search: params[:zipcode])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forecast_params
      params.fetch(:forecast, {}).permit(:search)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def dashboard

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/forecasts/_form.html.slim
= form_for @forecast do |f|
  - if @forecast.errors.any?
    #error_explanation
      h2 = "#{pluralize(@forecast.errors.count, "error")} prohibited this forecast from being saved:"
      ul
        - @forecast.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/forecasts/edit.html.slim
h1 Editing forecast

== render 'form'

=> link_to 'Show', @forecast
'|
=< link_to 'Back', forecasts_path

app/views/forecasts/index.html.slim
h1 Listing forecasts

table
  thead
    tr
      th
      th
      th

  tbody
    - @forecasts.each do |forecast|
      tr
        td = link_to 'Show', forecast
        td = link_to 'Edit', edit_forecast_path(forecast)
        td = link_to 'Destroy', forecast, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Forecast', new_forecast_path

app/views/forecasts/new.html.slim
h1 New forecast

== render 'form'

= link_to 'Back', forecasts_path

app/views/forecasts/show.html.slim
p.mt-3
	-if @cached
		| Cached
	-else
		| Not Cached

=cache @forecast.cache_key_with_version, skip_digest: true, expires_in: (Rails.env.production? ? 30.minutes : 5.seconds)

	#currently
		=image_tag @forecast.icon_image

		.temp-group
			#current-temp
				| #{@forecast.current_temp.round} &deg;F
			#today-lo
				| #{@forecast.low_temp.round} &deg;F
			#today-hi
				| #{@forecast.high_temp.round} &deg;F

	h1 =@forecast.location

	h2 =@forecast.location.zipcode

	hr

	ol#extended-forecasts
		-@forecast.extended_forecasts.each do |ef|
			li
				.day
					= ef.date.strftime("%^a")
				.lo
					| #{ef.low_temp.round} &deg;F
				.hi
					| #{ef.high_temp.round} &deg;F

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    
    title
      | Sun and Sleet

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body

    -if flash[:alert]
      .alert.alert-danger(role="alert")
        =flash[:alert]
        button(type="button" class="close" data-dismiss="alert" aria-label="Close")
          span(aria-hidden="true")
            | &times;

    nav.navbar.navbar-expand-lg.navbar-light.bg-light
      a.navbar-brand[href="#{root_path}"]
        | Sun and Sleet
      button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
        span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        ul.navbar-nav.mr-auto

        =render 'shared/search'

  	.container
  		.row
  			.col
			    = yield

    footer.container
      .row
        .col
          | Hire Ryan Detert - #{link_to "ryanforyou.com", "https://ryanforyou.com", target: :blank}

app/views/main/dashboard.html.slim
h1
	| Sun and Sleet


=render 'shared/search'

app/views/shared/_search.html.slim
=form_for Forecast.new, class: 'form-inline my-2 my-lg-0' do |f|
	.row
		.col
			=f.text_field :search, placeholder: 'City, State or Zip Code', class: 'form-control mr-sm-2'
		.col
			=f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'